### ISSUE TITLE
Regrouper les agences par zone

### ISSUE THREAD

**Issue by gbertherat** [adriens/web-generative-art-temps-attente-opt#15]
Interroger l'API sur différentes communes pour regrouper les agences par zone.

**Comment by adriens** [comment]
Un p'tit screenshot 🙏

**Comment by gbertherat** [comment]
@adriens 
![image](https://user-images.githubusercontent.com/61923651/101292505-fe0b4000-3863-11eb-9d38-cb6474f6064d.png)
